# Generated by Django 3.2 on 2021-04-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobility',
            fields=[
                ('date', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('mobility_recreation', models.FloatField(blank=True, null=True)),
                ('mobility_grocery', models.FloatField(blank=True, null=True)),
                ('mobility_parks', models.FloatField(blank=True, null=True)),
                ('mobility_transit', models.FloatField(blank=True, null=True)),
                ('mobility_work', models.FloatField(blank=True, null=True)),
                ('mobility_residential', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobility',
                'managed': False,
            },
        ),
    ]
